### ISSUE TITLE
Get rid of block content entities

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#11]
Or node entities?

Having trouble justifying the two of them since the differences are largely to do with rendering.

**Comment by balsama** [comment]
Some input from the twitterverse:
https://twitter.com/balsama/status/892180665336299521

Takeaways:
* At least some agree that blocks and nodes overlap.
* We should definitely get rid of one, and since nodes are the current de facto standard, it should probably be blocks that we get rid of.
* Let's just name nodes "Pages" for now. Not perfect, but I don't see any better options presenting themselves.
* /admin/content should be a Lightning Search powered, cross entity search page that automatically adds new entity types to the index as they are defined. I'll open a separate issue for that.

**Comment by phenaproxima** [comment]
Fixed by #13.
