### ISSUE TITLE
Error: The profile headless_lightning does not exist.

### ISSUE THREAD

**Issue by arisaves** [acquia/headless-lightning#118]
Hi there! Been using headless lightning for about a year; having an issue since running a new build yesterday.

I'm using docker instead of blt but an otherwise normal build. A fresh install from this repository brings down 8.6.x-dev version of Drupal core, and then produces a 500 error.

I've attached some screenshots for reference.

The error:
<img width="510" alt="screen shot 2018-12-19 at 5 47 05 pm" src="https://user-images.githubusercontent.com/886231/50256997-60887e80-03b6-11e9-9a13-1839038c1232.png">

The watchdog output:
<img width="1257" alt="screen shot 2018-12-19 at 4 54 50 pm" src="https://user-images.githubusercontent.com/886231/50257005-67af8c80-03b6-11e9-8b20-c03c4297a2b6.png">

[Update] I've isolated the issue to the install profile by attempting installs with lightning + other install profiles.

Thanks in advance for any help!

**Comment by arisaves** [comment]
Some updates:

- I was able to get around this by changing some permissions and increasing my memory limit
- Still kind of curious as to why so much memory is required

**Comment by phenaproxima** [comment]
Thanks for the report, @arisaves. Composer is very much a memory hog, and the more dependencies there are in a project (and, like many Drupal projects, Headless Lightning has _a lot_ of them), the more memory is required to resolve them. I recommend a solid 2 GB, and if it would be helpful, I'm sure we could document this in our installation instructions.
