### ISSUE TITLE
Consider making the edit form the canonical URL for all entities.

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#12]
Ideas:
* no link to /node/1
* ~~get 301 to admin/jsonapi/node/{uuid}~~
* make admin content form has link to edit form and URL to json rep

**Comment by phenaproxima** [comment]
This is partially implemented by acquia/lightning#423.

**Comment by phenaproxima** [comment]
Fixed in #23.

**Comment by balsama** [comment]
Looks like we forgot the redirect on new node creation. Reopening.

**Comment by phenaproxima** [comment]
Fixed in #25.
