### ISSUE TITLE
Switching to `dev` makes it hard to install other modules

### ISSUE THREAD

**Issue by paulsheldrake** [acquia/headless-lightning#121]
This commit 9815cf2fd3a43f2bb08196a622918410d0e90da9 now makes it hard to install regular modules because they fail minimum stability requirements.   Can you please stay on stable releases?

Thank you

**Comment by balsama** [comment]
Hi. That commit is needed for development. Note that it's not in a tagged release of Headless Lightning. You should only be using tagged releases for a stable app. E.g.:

```
composer require acquia/headless-lightning:^1.0
```
<img width="986" alt="terminal_ _less_ _git_log_--graph_--oneline_--all_ _bash" src="https://user-images.githubusercontent.com/1536654/52573775-d9211f80-2de8-11e9-8093-c50546da206c.png">

**Comment by paulsheldrake** [comment]
🤦‍♂️ Sorry, that was my bad.   Thanks for pointing out the obvious to me
