### ISSUE TITLE
Remove unused admin features from UI

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#2]
I don't think we need to remove actual routes, but we shouldn't clutter the UI with things strictly related to the display of content. We should remove (for all content entities):

- Manage Display tab
- Menu settings
- Display settings (post information)
- I've never cared for the "sticky" and "promoted" options and would prefer to remove those too
- Display modes link on /admin/structure
- Block layout

**Comment by phenaproxima** [comment]
I think this is pretty done.
