### ISSUE TITLE
JSON API is throwing 500 errors

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#24]
This is seemingly only reproducible in Headless Lightning for some reason. Steps to reproduce:

1. Add a basic page
2. Visit it at jsonapi/node/page/{uuid}

500

I was troubleshooting a likely related issue this morning that pointed towards the Meta Tag module as generally not playing nicely with JSON API. But I haven't confirmed that that's the case or that they issues are related.

**Comment by phenaproxima** [comment]
This is addressed by acquia/lightning#424.

**Comment by balsama** [comment]
Fixes in Lightning 7279724d33ebdeea4a8ac03baef695ecffcd9992
