### ISSUE TITLE
API Access page cleanup

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#34]
* Title should be "API Access" (not "Access Control")
* curl example is inconsistent in how it marks variables
* Key configuration should probably be in here somewhere (current path: admin/config/people/simple_oauth)

**Comment by phenaproxima** [comment]
> curl example is inconsistent in how it marks variables

Can you elaborate on this?

> Key configuration should probably be in here somewhere

Not a problem, can you provide the link title and description?

**Comment by balsama** [comment]
Link title: API Settings
Description:
Allows you to configure certain settings for the API including token expiration and the location of your keys.

**Comment by phenaproxima** [comment]
Fixed in #36.
