### ISSUE TITLE
Tabs on content page should reflect Content Models page

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#42]
Specifically, there should be tabs that link to listings of:
* Content
* Media
* Taxonomy
* Users

The scheduled updates tab is already there, which isn't ideal, but a better place for it isn't obvious to me. Perhaps as a local task next to "Add content"?

**Comment by phenaproxima** [comment]
We discussed this a bit and concluded that this doesn't make a whole lot of sense -- instead, we concluded that we'll do the following to the Content page:

* Make Scheduled Updates tab a child of Content
* Remove the Files tab
