### ISSUE TITLE
Remove Users from Content Model UI

### ISSUE THREAD

**Issue by phenaproxima** [acquia/headless-lightning#46]
In discussion with @balsama, we agreed that, in a fully decoupled Drupal setup, users do not really count as content. I think our thinking probably got muddied by the fact that they are content entities. Anyway, we agreed that user accounts are part of the access layer, not the content layer, and therefore the link to the user listing from the API Access page is sufficient. Content Model UI should not make any mention of user accounts as content models.

**Comment by phenaproxima** [comment]
Fixed in #47.

**Comment by balsama** [comment]
Whoops. Looks like #47 failed to remove the Users tab from the Content Models page:

<img width="606" alt="content_models___headless_lightning_-_nightly_build" src="https://user-images.githubusercontent.com/1536654/29336386-99fd3d26-81db-11e7-9c11-2131c200be5d.png">
