### ISSUE TITLE
Consolidate content modeling

### ISSUE THREAD

**Issue by balsama** [acquia/headless-lightning#5]
It would be nice if we could consolidate links to all of the entity bundle admin screens in one place and standardize the URL structure. E.g.:

Type | Current | Suggested
-|-|-
Nodes | /admin/structure/types | admin/structure/pages
Taxonomy | /admin/structure/taxonomy | /admin/structure/categories
Media | /admin/structure/media | admin/structure/media
Users | /admin/config/people/accounts | /admin/structure/users

* Users a little different - not bundle-able
* We really need a better name for Node/Content. Content implies that it's the only place content is stored. Nodes doesn't mean anything to most
* Some of the local task actions (Crean new "XX") are different too from the URLs/other references. We should standardize those.

**Comment by balsama** [comment]
Having issues with changing verbiage. Perhaps just change UI and leave language the same. Perhaps we could revisit after MVP?

**Comment by phenaproxima** [comment]
As discussed earlier, we decided not to rename anything. It would be a complex and far-reaching undertaking, albeit an important one, but I think we agreed that it's not MVP.

**Comment by balsama** [comment]
I think we can close this on #20. I'll open up a followup for tweaks.
